const clothes = [
    { wording: "Chemise", categoryItem: 1 },
  { wording: "Jeans", categoryItem: 1 },
  { wording: "Veste en cuir", categoryItem: 1 },
  { wording: "Chaussures de sport", categoryItem: 1 },
  { wording: "Cravate", categoryItem: 1 },
  { wording: "Pullover", categoryItem: 1 },
  { wording: "Chapeau", categoryItem: 1 },
  { wording: "Costume", categoryItem: 1 },
  { wording: "Montre", categoryItem: 1 },
  { wording: "Shorts", categoryItem: 1 },
  { wording: "Chaussettes", categoryItem: 1 },
  { wording: "Pantalon de costume", categoryItem: 1 },
  { wording: "Ceinture en cuir", categoryItem: 1 },
  { wording: "T-shirt", categoryItem: 1 },
  { wording: "Blazer", categoryItem: 1 },
  { wording: "Chaussures habillées", categoryItem: 1 },
  { wording: "Casquette", categoryItem: 1 },
  { wording: "Pull à col roulé", categoryItem: 1 },
  { wording: "Manteau en laine", categoryItem: 1 },
  { wording: "Polo", categoryItem: 1 },
  { wording: "Robe", categoryItem: 2 },
  { wording: "Talons hauts", categoryItem: 2 },
  { wording: "Sac à main", categoryItem: 2 },
  { wording: "Chaussures plates", categoryItem: 2 },
  { wording: "Jupe", categoryItem: 2 },
  { wording: "Blouse", categoryItem: 2 },
  { wording: "Collier", categoryItem: 2 },
  { wording: "Leggings", categoryItem: 2 },
  { wording: "Chapeau de soleil", categoryItem: 2 },
  { wording: "Maillot de bain", categoryItem: 2 },
  { wording: "Pantalon large", categoryItem: 2 },
  { wording: "Bottes", categoryItem: 2 },
  { wording: "Pullover", categoryItem: 2 },
  { wording: "Chapeau en laine", categoryItem: 2 },
  { wording: "Sandales", categoryItem: 2 },
  { wording: "Blazer élégant", categoryItem: 2 },
  { wording: "Sac fourre-tout", categoryItem: 2 },
  { wording: "Collants", categoryItem: 2 },
  { wording: "Haut sans manches", categoryItem: 2 },
];

module.exports = clothes;