const fashionAccessories = [
    { wording: "Écharpe", categoryItem: 4 },
    { wording: "Montre-bracelet", categoryItem: 4 },
    { wording: "Chapeau fedora", categoryItem: 4 },
    { wording: "Lunettes de soleil aviateur", categoryItem: 4 },
    { wording: "Cravate", categoryItem: 4 },
    { wording: "Boucles d'oreilles", categoryItem: 4 },
    { wording: "Ceinture en cuir", categoryItem: 4 },
    { wording: "Gants en laine", categoryItem: 4 },
    { wording: "Parapluie pliable", categoryItem: 4 },
    { wording: "Sac à dos en toile", categoryItem: 4 },
    { wording: "Portefeuille en cuir", categoryItem: 4 },
    { wording: "Casquette", categoryItem: 4 },
    { wording: "Collier de perles", categoryItem: 4 },
    { wording: "Bretelles", categoryItem: 4 },
    { wording: "Foulard en soie", categoryItem: 4 },
    { wording: "Chaussettes colorées", categoryItem: 4 },
    { wording: "Béret en laine", categoryItem: 4 },
    { wording: "Broche élégante", categoryItem: 4 },
    { wording: "Lunettes de lecture", categoryItem: 4 },
    { wording: "Cravate en tricot", categoryItem: 4 },
    { wording: "Bague en argent", categoryItem: 4 },
    { wording: "Foulard léger", categoryItem: 4 },
    { wording: "Casquette de baseball", categoryItem: 4 },
    { wording: "Pochette de costume", categoryItem: 4 },
    { wording: "Châle en cachemire", categoryItem: 4 },
    { wording: "Boutons de manchette", categoryItem: 4 },
    { wording: "Chaussures à talons", categoryItem: 4 },
    { wording: "Chapeau de paille", categoryItem: 4 },
    { wording: "Boucle de ceinture", categoryItem: 4 },
    { wording: "Épinglette élégante", categoryItem: 4 },
    { wording: "Porte-monnaie en cuir", categoryItem: 4 },
    { wording: "Gants en cuir", categoryItem: 4 },
    { wording: "Parapluie coloré", categoryItem: 4 },
    { wording: "Sac à main chic", categoryItem: 4 },
    { wording: "Chaussettes hautes", categoryItem: 4 },
    { wording: "Cravate en soie", categoryItem: 4 },
    { wording: "Bandeau de sport", categoryItem: 4 },
    { wording: "Bijoux en or", categoryItem: 4 },
    { wording: "Châle élégant", categoryItem: 4 },
    { wording: "Casquette de camionneur", categoryItem: 4 },
    { wording: "Étui à lunettes", categoryItem: 4 },
    { wording: "Foulard en dentelle", categoryItem: 4 },
    { wording: "Boutons de chemise", categoryItem: 4 },
    { wording: "Chaussures de sport", categoryItem: 4 },
    { wording: "Chapeau de pluie", categoryItem: 4 },
    { wording: "Bijoux fantaisie", categoryItem: 4 },
    { wording: "Parapluie élégant", categoryItem: 4 }
  ];
  
module.exports = fashionAccessories;