const foods = [
    {"wording":"Pain","categoryItem":18},
    {"wording":"Lait","categoryItem":18},
    {"wording":"Oeufs","categoryItem":18},
    {"wording":"Riz","categoryItem":18},
    {"wording":"Pâtes","categoryItem":18},
    {"wording":"Pommes de terre","categoryItem":18},
    {"wording":"Poulet","categoryItem":18},
    {"wording":"Dinde","categoryItem":18},
    {"wording":"Escalope","categoryItem":18},
    {"wording":"Poisson","categoryItem":18},
    {"wording":"Tomates","categoryItem":18},
    {"wording":"Carottes","categoryItem":18},
    { "wording": "Salade", "categoryItem": 18 },
    { "wording": "Yaourt", "categoryItem": 18 },
    { "wording": "Fromage", "categoryItem": 18 },
    { "wording": "Beurre", "categoryItem": 18 },
    { "wording": "Céréales", "categoryItem": 18 },
    { "wording": "Conserve de tomates", "categoryItem": 18 },
    { "wording": "Haricots en conserve", "categoryItem": 18 },
    { "wording": "Soupe en conserve", "categoryItem": 18 },
    { "wording": "Pommes", "categoryItem": 18 },
    { "wording": "Bananes", "categoryItem": 18 },
    { "wording": "Oranges", "categoryItem": 18 },
    { "wording": "Poires", "categoryItem": 18 },
    { "wording": "Fraises", "categoryItem": 18 },
    { "wording": "Framboises", "categoryItem": 18 },
    { "wording": "Myrtilles", "categoryItem": 18 },
    { "wording": "Ananas", "categoryItem": 18 },
    { "wording": "Melon", "categoryItem": 18 },
    { "wording": "Mangue", "categoryItem": 18 },
    { "wording": "Pêches", "categoryItem": 18 },
    { "wording": "Abricots", "categoryItem": 18 },
    { "wording": "Prunes", "categoryItem": 18 },
    { "wording": "Cerises", "categoryItem": 18 },
    { "wording": "Raisins", "categoryItem": 18 },
    { "wording": "Brocoli", "categoryItem": 18 },
    { "wording": "Chou-fleur", "categoryItem": 18 },
    { "wording": "Aubergine", "categoryItem": 18 },
    { "wording": "Courgette", "categoryItem": 18 },
    { "wording": "Poivron", "categoryItem": 18 },
    { "wording": "Pomme de cajou", "categoryItem": 18 },
    { "wording": "Mandarines", "categoryItem": 18 },
    { "wording": "Kiwi", "categoryItem": 18 },
    { "wording": "Anchois", "categoryItem": 18 },
    { "wording": "Avocat", "categoryItem": 18 },
    { "wording": "Bacon", "categoryItem": 18 },
    { "wording": "Baguette", "categoryItem": 18 },
    { "wording": "Baies de goji", "categoryItem": 18 },
    { "wording": "Barre de céréales", "categoryItem": 18 },
    { "wording": "Basilic", "categoryItem": 18 },
    { "wording": "Bœuf", "categoryItem": 18 },
    { "wording": "Biscuits", "categoryItem": 18 },
    { "wording": "Brochettes", "categoryItem": 18 },
    { "wording": "Cacao", "categoryItem": 18 },
    { "wording": "Café", "categoryItem": 18 },
    { "wording": "Canneberges", "categoryItem": 18 },
    { "wording": "Cannelle", "categoryItem": 18 },
    { "wording": "Champignons", "categoryItem": 18 },
    { "wording": "Chocolat", "categoryItem": 18 },
    { "wording": "Chorizo", "categoryItem": 18 },
    { "wording": "Ciboulette", "categoryItem": 18 },
    { "wording": "Citron", "categoryItem": 18 },
    { "wording": "Compote", "categoryItem": 18 },
    { "wording": "Concombre", "categoryItem": 18 },
    { "wording": "Cornichons", "categoryItem": 18 },
    { "wording": "Crème fraîche", "categoryItem": 18 },
    { "wording": "Croissants", "categoryItem": 18 },
    { "wording": "Curry", "categoryItem": 18 },
    { "wording": "Dattes", "categoryItem": 18 },
    { "wording": "Eau minérale", "categoryItem": 18 },
    { "wording": "Échalotes", "categoryItem": 18 },
    { "wording": "Épinards", "categoryItem": 18 },
    { "wording": "Feta", "categoryItem": 18 },
    { "wording": "Foie gras", "categoryItem": 18 },
    { "wording": "Frites", "categoryItem": 18 },
    { "wording": "Gingembre", "categoryItem": 18 },
    { "wording": "Gruyère", "categoryItem": 18 },
    { "wording": "Guacamole", "categoryItem": 18 },
    { "wording": "Haricots verts", "categoryItem": 18 },
    { "wording": "Huile d'olive", "categoryItem": 18 },
    { "wording": "Jambon", "categoryItem": 18 },
    { "wording": "Ketchup", "categoryItem": 18 },
    { "wording": "Laitue", "categoryItem": 18 },
    { "wording": "Lentilles", "categoryItem": 18 },
    { "wording": "Maïs", "categoryItem": 18 },
    { "wording": "Mayonnaise", "categoryItem": 18 },
    { "wording": "Miel", "categoryItem": 18 },
    {"wording":"Miel de manuka","categoryItem":18},
    {"wording":"Miettes de bacon","categoryItem":18},
    {"wording":"Miso","categoryItem":18},
    {"wording":"Muffins","categoryItem":18},
    {"wording":"Muscade","categoryItem":18},
    {"wording":"Navets","categoryItem":18},
    {"wording":"Nectarines","categoryItem":18},
    {"wording":"Noisettes","categoryItem":18},
    {"wording":"Noix de cajou","categoryItem":18},
    {"wording":"Noix de coco","categoryItem":18},
    {"wording":"Noix de muscade","categoryItem":18},
    {"wording":"Nouilles","categoryItem":18},
    {"wording":"Nutella","categoryItem":18},
    {"wording":"Œufs de caille","categoryItem":18},
    {"wording":"Œufs de poule","categoryItem":18},
    { "wording": "Oignons", "categoryItem": 18 },
    { "wording": "Origan", "categoryItem": 18 },
    { "wording": "Pain", "categoryItem": 18 },
    { "wording": "Paprika", "categoryItem": 18 },
    { "wording": "Pâtes", "categoryItem": 18 },
    { "wording": "Patates douces", "categoryItem": 18 },
    { "wording": "Pâtes à pizza", "categoryItem": 18 },
    { "wording": "Pêches au sirop", "categoryItem": 18 },
    { "wording": "Pépites de chocolat", "categoryItem": 18 },
    { "wording": "Persil", "categoryItem": 18 },
    { "wording": "Pesto", "categoryItem": 18 },
    { "wording": "Petits pois", "categoryItem": 18 },
    { "wording": "Poireaux", "categoryItem": 18 },
    { "wording": "Poivre", "categoryItem": 18 },
    { "wording": "Pomme de terre", "categoryItem": 18 },
    { "wording": "Poulet", "categoryItem": 18 },
    { "wording": "Quinoa", "categoryItem": 18 },
    { "wording": "Riz", "categoryItem": 18 },
    { "wording": "Riz basmati", "categoryItem": 18 },
    { "wording": "Riz complet", "categoryItem": 18 },
    { "wording": "Roquette", "categoryItem": 18 },
    { "wording": "Rosbif", "categoryItem": 18 },
    { "wording": "Safran", "categoryItem": 18 },
    { "wording": "Saint-Jacques", "categoryItem": 18 },
    { "wording": "Saumon", "categoryItem": 18 },
    { "wording": "Saucisses", "categoryItem": 18 },
    { "wording": "Saucisson", "categoryItem": 18 },
    { "wording": "Seigle", "categoryItem": 18 },
    { "wording": "Sel", "categoryItem": 18 },
    { "wording": "Sésame", "categoryItem": 18 },
    { "wording": "Steak", "categoryItem": 18 },
    { "wording": "Sucre", "categoryItem": 18 },
    { "wording": "Thon", "categoryItem": 18 },
    { "wording": "Thym", "categoryItem": 18 },
    { "wording": "Tomates", "categoryItem": 18 },
    { "wording": "Tomates cerises", "categoryItem": 18 },
    { "wording": "Tomates en conserve", "categoryItem": 18 },
    { "wording": "Tomates séchées", "categoryItem": 18 },
    { "wording": "Tortillas", "categoryItem": 18 },
    { "wording": "Truite", "categoryItem": 18 },
    { "wording": "Vanille", "categoryItem": 18 },
    { "wording": "Vinaigre", "categoryItem": 18 },
    { "wording": "Vinaigre balsamique", "categoryItem": 18 },
    { "wording": "Vinaigre de vin", "categoryItem": 18 },
    { "wording": "Yaourt grec", "categoryItem": 18 },
    { "wording": "Yaourt nature", "categoryItem": 18 },
    { "wording": "Zeste de citron", "categoryItem": 18 },
    { "wording": "Zeste d'orange", "categoryItem": 18 }
];

module.exports = foods;