const shoes = [
    { wording: "Baskets", categoryItem: 3 },
    { wording: "Bottes de randonnée", categoryItem: 3 },
    { wording: "Escarpins", categoryItem: 3 },
    { wording: "Chaussures de sport", categoryItem: 3 },
    { wording: "Tongs", categoryItem: 3 },
    { wording: "Bottes de pluie", categoryItem: 3 },
    { wording: "Sandales", categoryItem: 3 },
    { wording: "Chaussons", categoryItem: 3 },
    { wording: "Mocassins", categoryItem: 3 },
    { wording: "Bottes à talons", categoryItem: 3 },
    { wording: "Chaussures plates", categoryItem: 3 },
    { wording: "Baskets montantes", categoryItem: 3 },
    { wording: "Chaussures de soirée", categoryItem: 3 },
    { wording: "Chaussures de marche", categoryItem: 3 },
    { wording: "Bottes de moto", categoryItem: 3 },
    { wording: "Espadrilles", categoryItem: 3 },
    { wording: "Ballerines", categoryItem: 3 },
    { wording: "Chaussures à talons compensés", categoryItem: 3 },
    { wording: "Chaussures à lacets", categoryItem: 3 },
    { wording: "Chaussures de danse", categoryItem: 3 },
    { wording: "Chaussures de skate", categoryItem: 3 },
    { wording: "Chaussures de sécurité", categoryItem: 3 },
    { wording: "Bottes en cuir", categoryItem: 3 },
    { wording: "Sabots", categoryItem: 3 },
    { wording: "Chaussons en laine", categoryItem: 3 },
    { wording: "Chaussures Oxford", categoryItem: 3 },
    { wording: "Chaussures de plage", categoryItem: 3 },
    { wording: "Chaussures de jogging", categoryItem: 3 },
    { wording: "Talons aiguilles", categoryItem: 3 },
    { wording: "Chaussures de mariage", categoryItem: 3 },
  ];

module.exports = shoes;